Controllers films users TZ10
romakrnv/java-filmorate pull request #2
Opened 2024-06-27 21:27 UTC by romakrnv

2024-06-27 21:40 UTC, romakrnv commented
Привет!
Упали 3 теста, первый связан с пустым name, по ТЗ сказано "имя для отображения может быть пустым — в таком случае будет использован логин;", что дало мне предположение, что юзера бы создаём тогда с именем равным null

Другие 2 связаны с Duration, видимо постман не умеет правильно конвертить Duration или тесты не совсем верно написаны, сравнивал просто созданием, у меня всё совпадает.

Спасибо)

2024-06-28 20:44 UTC, z8q requested changes

2024-06-28 20:44 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
notBlank проверяет на notNull тоже

2024-06-28 20:44 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return user;
Из тз
```
имя для отображения может быть пустым — в таком случае будет использован логин;
```
Тут падает тест Create user with empty name, потому что мы не заполняем пустой name логином

2024-06-28 20:44 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Duration duration;
Из тз
```
продолжительность фильма должна быть положительным числом
```
предполагаю что здесь хотят тип Integer например

это про падающие тесты Film create и Film update

2024-06-28 20:44 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
В модели Film можно попробовать использовать валидационную аннотацию Size с параметром 200
```
@Size(min = 1, max = 200)
```

2024-06-28 20:44 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDuration().isZero() || film.getDuration().isNegative()) {
Если duration будет числом, можно попробовать валидационную аннотацию Positive

2024-06-28 20:44 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull
тут можно заменить на notBlank

2024-07-07 00:47 UTC, z8q requested changes

2024-07-07 00:47 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setDuration(Duration duration) {
Возможно тесты не проходят, потому что созданы свои сеттеры и геттеры для поля duration. Можно попробовать их убрать, чтобы использовались те, которые создаются ломбоком и работают с типом long

2024-07-07 00:47 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Long id;
Нужно еще поставить модификаторы private на поля класса

2024-07-07 00:47 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setDuration(Duration duration) {
в User тоже

2024-07-10 19:29 UTC, z8q approved these changes

2024-07-12 02:47 UTC, merged